// muon - Multi-platform GUI application framework that uses CEF as its backend
// Copyright (c) Kouji Matsui. (@kekyo@mi.kekyo.net)
// Under MIT.
// https://github.com/kekyo/muon-ui

import { randomBytes } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

/**
 * Import-side capability rule for muon plugin virtual modules.
 */
export interface MuonCapabilityImportOptions {
  /**
   * Importer path globs relative to the bundler project root.
   */
  sources?: readonly string[];
  /**
   * NPM package names allowed to import the virtual module.
   */
  packages?: readonly string[];
  /**
   * Plugin function path globs allowed for matching importers.
   */
  allow: readonly string[];
  /**
   * Plugin entry name that supplied this rule.
   *
   * @internal
   */
  pluginName?: string;
}

/**
 * Capability import configuration shared by bundler integrations.
 */
export interface MuonCapabilityOptions {
  /**
   * Capability imports allowed by importer path.
   */
  imports?: readonly MuonCapabilityImportOptions[];
  /**
   * Known public plugin function paths available for wildcard export expansion.
   *
   * @remarks Exact `imports[].allow` entries do not require this catalog.
   * Wildcard entries are expanded against these paths only when generating
   * virtual module named exports; runtime permission policies keep the original
   * wildcard patterns.
   */
  functionPaths?: readonly string[];
}

/**
 * Runtime capability policy generated for muon-core.
 */
export interface MuonCapabilityRuntimeEntry {
  /**
   * Opaque capability id embedded into generated virtual modules.
   */
  id: string;
  /**
   * Plugin function path globs allowed for this capability.
   */
  allow: readonly string[];
}

/**
 * Runtime plugin entry generated for muon-core config overlays.
 */
export interface MuonRuntimePluginEntryConfig {
  /**
   * Plugin entry name.
   */
  name: string;
  /**
   * Optional 64-character hexadecimal SHA-256 digest of the final external
   * `.so` or `.dll` file bytes followed by the decoded `salt` bytes.
   *
   * @remarks Calculate this after all library post-processing, including
   * stripping and code signing. It is not supported for `internal`.
   */
  signature?: string;
  /**
   * Optional hex-encoded salt whose decoded bytes are appended when checking
   * the plugin signature.
   *
   * @remarks Required when `signature` is specified. It is not supported for
   * `internal`.
   */
  salt?: string;
  /**
   * Plugin-defined string key-value configuration entries.
   */
  config?: Readonly<Record<string, string>>;
  /**
   * Plugin function path globs allowed for this plugin entry.
   */
  allow: readonly string[];
}

/**
 * Runtime plugin configuration generated for validate mode.
 */
export interface MuonCapabilityRuntimePluginConfig {
  /**
   * Plugin exposure mode.
   */
  mode: "validate";
  /**
   * Plugin bridge page URL allowlist.
   */
  pages?: readonly string[];
  /**
   * External plugin path override.
   */
  path?: string;
  /**
   * Plugin loading allowlist override.
   */
  plugins?: readonly MuonRuntimePluginEntryConfig[];
  /**
   * Capability policies consumed by muon-core.
   */
  capabilities: readonly MuonCapabilityRuntimeEntry[];
}

/**
 * Runtime plugin configuration for simple window-global exposure.
 */
export interface MuonSimpleRuntimePluginConfig {
  /**
   * Plugin exposure mode.
   */
  mode: "simple";
  /**
   * Plugin bridge page URL allowlist.
   */
  pages?: readonly string[];
  /**
   * External plugin path override.
   */
  path?: string;
  /**
   * Plugin loading allowlist override.
   */
  plugins?: readonly MuonRuntimePluginEntryConfig[];
}

/**
 * Runtime plugin configuration generated by a build integration.
 */
export type MuonRuntimePluginConfig =
  | MuonCapabilityRuntimePluginConfig
  | MuonSimpleRuntimePluginConfig;

/**
 * Resolved virtual module.
 */
export interface MuonResolvedCapabilityModule {
  /**
   * Bundler-internal virtual id.
   */
  id: string;
}

/**
 * Bundler-independent virtual module resolver.
 */
export interface MuonCapabilityModuleResolver {
  /**
   * Resolves a muon virtual module specifier for one importer.
   */
  resolveId: (
    source: string,
    importer: string | undefined,
  ) => MuonResolvedCapabilityModule | undefined;
  /**
   * Loads the generated source for a resolved virtual module id.
   */
  load: (id: string) => string | undefined;
  /**
   * Returns runtime plugin config generated from all capability rules.
   */
  getRuntimePluginConfig: () => MuonCapabilityRuntimePluginConfig;
}

interface ParsedCapabilitySpecifier {
  moduleName: string;
  namespace: string;
}

interface ResolvedRule {
  index: number;
  id: string;
  rule: MuonCapabilityImportOptions;
  namespace: string;
  moduleName: string;
  functionPaths: readonly string[];
}

const virtualModulePrefix = "\0muon-capability:";
const capabilityIdByteLength = 16;
const moduleNamePattern =
  /^[A-Za-z_$][A-Za-z0-9_$]*:[A-Za-z_$][A-Za-z0-9_$]*(?:\.[A-Za-z_$][A-Za-z0-9_$]*)*$/u;
const jsIdentifierPattern = /^[A-Za-z_$][A-Za-z0-9_$]*$/u;
const defaultMuonCapabilityFunctionPaths = [
  "muon.browser.reload",
  "muon.browser.hardReload",
  "muon.browser.toggleFullscreen",
  "muon.browser.enterFullscreen",
  "muon.browser.exitFullscreen",
  "muon.browser.zoomIn",
  "muon.browser.zoomOut",
  "muon.browser.resetZoom",
  "muon.browser.show",
  "muon.browser.hide",
  "muon.browser.focus",
  "muon.browser.blur",
  "muon.browser.minimize",
  "muon.browser.maximize",
  "muon.browser.restore",
  "muon.browser.setTitleBarVisibility",
  "muon.browser.setTitleBarIcon",
  "muon.browser.getWindowBounds",
  "muon.browser.setWindowBounds",
  "muon.browser.setContextMenuItems",
  "muon.browser.clearContextMenuItems",
  "muon.browser.createTray",
  "muon.browser.setTrayMenu",
  "muon.browser.setTrayIcon",
  "muon.browser.setTrayTooltip",
  "muon.browser.removeTray",
  "muon.browser.close",
  "muon.browser.shutdown",
  "muon.browser.recycle",
  "muon.environments.getVariables",
  "muon.environments.getConfigValues",
  "muon.environments.getCommandLine",
  "muon.environments.getProcessId",
  "muon.environments.getRuntimeInfo",
  "muon.environments.getAutostart",
  "muon.environments.setAutostart",
  "muon.executor.spawn",
  "muon.executor.loadLibrary",
  "muon.fs.readFile",
  "muon.fs.writeFile",
  "muon.fs.readTextFile",
  "muon.fs.writeTextFile",
  "muon.fs.stat",
  "muon.fs.lstat",
  "muon.fs.exists",
  "muon.fs.access",
  "muon.fs.readdir",
  "muon.fs.mkdir",
  "muon.fs.rm",
  "muon.fs.unlink",
  "muon.fs.rmdir",
  "muon.fs.rename",
  "muon.fs.copyFile",
  "muon.fs.appendFile",
  "muon.fs.appendTextFile",
  "muon.fs.truncate",
  "muon.fs.realpath",
  "muon.fs.readlink",
  "muon.fs.symlink",
  "muon.fs.watch",
  "muon.fs.dialogs.selectFile",
  "muon.fs.dialogs.selectFiles",
  "muon.fs.dialogs.selectDirectory",
  "muon.fs.dialogs.selectDirectories",
  "muon.fs.dialogs.selectSaveFile",
  "muon.launcher.getSettings",
  "muon.launcher.setSettings",
  "muon.launcher.triggerUpdate",
] as const;

const normalizePath = (path: string): string =>
  (path.split("?")[0] ?? "").replaceAll("\\", "/");

const createCapabilityId = (usedIds: Set<string>): string => {
  for (;;) {
    const id = `cap-${randomBytes(capabilityIdByteLength).toString("hex")}`;
    if (!usedIds.has(id)) {
      usedIds.add(id);
      return id;
    }
  }
};

const parseCapabilitySpecifier = (
  source: string,
): ParsedCapabilitySpecifier | undefined => {
  if (!moduleNamePattern.test(source)) {
    return undefined;
  }
  const separator = source.indexOf(":");
  const namespace = `${source.slice(0, separator)}.${source.slice(separator + 1)}`;
  return {
    moduleName: source,
    namespace,
  };
};

const escapeRegExp = (source: string): string =>
  source.replace(/[\\^$+?.()|[\]{}]/gu, "\\$&");

const globToRegExp = (glob: string, separator: string): RegExp => {
  let source = "^";
  for (let index = 0; index < glob.length; index += 1) {
    const current = glob[index] ?? "";
    const next = glob[index + 1];
    if (current === "*" && next === "*") {
      source += ".*";
      index += 1;
      continue;
    }
    if (current === "*") {
      source += `[^${escapeRegExp(separator)}]*`;
      continue;
    }
    source += escapeRegExp(current);
  }
  source += "$";
  return new RegExp(source, "u");
};

const isGlobMatch = (glob: string, value: string, separator: string): boolean =>
  globToRegExp(glob, separator).test(value);

const containsGlob = (value: string): boolean => value.includes("*");

const toRootRelativeImporter = (root: string, importer: string): string =>
  normalizePath(relative(root, importer));

const readPackageName = (packageJsonPath: string): string | undefined => {
  try {
    const parsed = JSON.parse(readFileSync(packageJsonPath, "utf8")) as unknown;
    return typeof parsed === "object" &&
      parsed !== null &&
      !Array.isArray(parsed) &&
      typeof (parsed as { name?: unknown }).name === "string"
      ? (parsed as { name: string }).name
      : undefined;
  } catch {
    return undefined;
  }
};

const getImporterPackageName = (
  root: string,
  importer: string,
): string | undefined => {
  const normalizedRoot = normalizePath(root);
  const rootPackageJsonPath = join(root, "package.json");
  let directory = dirname(normalizePath(importer));
  for (;;) {
    const packageJsonPath = join(directory, "package.json");
    if (
      packageJsonPath !== rootPackageJsonPath &&
      existsSync(packageJsonPath)
    ) {
      return readPackageName(packageJsonPath);
    }
    if (normalizePath(directory) === normalizedRoot) {
      return undefined;
    }
    const parent = dirname(directory);
    if (parent === directory) {
      return undefined;
    }
    directory = parent;
  }
};

const matchesCapabilityRuleImporter = (
  rule: MuonCapabilityImportOptions,
  root: string,
  importer: string,
): boolean => {
  const relativeImporter = toRootRelativeImporter(root, importer);
  const sourceMatched =
    rule.sources?.some((pattern) =>
      isGlobMatch(normalizePath(pattern), relativeImporter, "/"),
    ) ?? false;
  if (sourceMatched) {
    return true;
  }

  const packageName = getImporterPackageName(root, importer);
  return packageName === undefined
    ? false
    : (rule.packages?.includes(packageName) ?? false);
};

const hasNamespaceFunctionAllow = (
  namespace: string,
  allow: readonly string[],
): boolean =>
  allow.some((entry) => {
    if (entry.startsWith(`${namespace}.`)) {
      return true;
    }
    return isGlobMatch(entry, `${namespace}.placeholder`, ".");
  });

const getExactExportName = (
  namespace: string,
  functionPath: string,
): string | undefined => {
  const prefix = `${namespace}.`;
  if (!functionPath.startsWith(prefix)) {
    return undefined;
  }
  const name = functionPath.slice(prefix.length);
  if (!jsIdentifierPattern.test(name)) {
    return undefined;
  }
  return name;
};

const getExportedFunctions = (
  namespace: string,
  allow: readonly string[],
  functionPaths: readonly string[],
): [string, string][] => {
  const exportedFunctions = new Map<string, string>();
  const addExport = (functionPath: string): void => {
    const exportName = getExactExportName(namespace, functionPath);
    if (exportName !== undefined && !exportedFunctions.has(exportName)) {
      exportedFunctions.set(exportName, functionPath);
    }
  };

  for (const entry of allow) {
    if (!containsGlob(entry)) {
      addExport(entry);
      continue;
    }
    for (const functionPath of functionPaths) {
      if (isGlobMatch(entry, functionPath, ".")) {
        addExport(functionPath);
      }
    }
  }
  return Array.from(exportedFunctions.entries());
};

const createFunctionPathCatalog = (
  functionPaths: readonly string[] | undefined,
): readonly string[] => {
  const catalog: string[] = [];
  const seen = new Set<string>();
  for (const functionPath of [
    ...defaultMuonCapabilityFunctionPaths,
    ...(functionPaths ?? []),
  ]) {
    if (!seen.has(functionPath)) {
      seen.add(functionPath);
      catalog.push(functionPath);
    }
  }
  return catalog;
};

const createRuleRuntimeEntry = (
  rule: MuonCapabilityImportOptions,
  id: string,
): MuonCapabilityRuntimeEntry => ({
  id,
  allow: [...rule.allow],
});

const validateCapabilityRule = (rule: MuonCapabilityImportOptions): void => {
  if (
    (rule.sources === undefined || rule.sources.length === 0) &&
    (rule.packages === undefined || rule.packages.length === 0)
  ) {
    throw new Error(
      "muon capability import rule requires sources or packages.",
    );
  }
};

const createModuleVirtualId = (rule: ResolvedRule): string =>
  `${virtualModulePrefix}${rule.index}:${rule.moduleName}`;

const parseModuleVirtualId = (
  id: string,
): { index: number; moduleName: string } | undefined => {
  if (!id.startsWith(virtualModulePrefix)) {
    return undefined;
  }
  const payload = id.slice(virtualModulePrefix.length);
  const separator = payload.indexOf(":");
  if (separator <= 0) {
    return undefined;
  }
  const index = Number.parseInt(payload.slice(0, separator), 10);
  if (!Number.isInteger(index) || index < 0) {
    return undefined;
  }
  return {
    index,
    moduleName: payload.slice(separator + 1),
  };
};

const createExecutorSpawnExport = (
  capabilityId: string,
  functionPath: string,
): string => `const __muonExecutorActiveProcesses = new Set();
const __muonExecutorEmptyBytes = new Uint8Array(0);
const __muonExecutorOwnerCallback = () => {};
const __muonExecutorAsyncDispose =
  typeof Symbol === "function" && typeof Symbol.asyncDispose === "symbol"
    ? Symbol.asyncDispose
    : null;
const __muonExecutorToBytes = (data) => {
  if (typeof data === "string") {
    return new TextEncoder().encode(data);
  }
  if (data instanceof ArrayBuffer) {
    return new Uint8Array(data);
  }
  if (ArrayBuffer.isView(data)) {
    return new Uint8Array(data.buffer, data.byteOffset, data.byteLength);
  }
  throw new TypeError("stdin data must be a string or BufferSource");
};
const __muonExecutorFromBase64 = (source) => {
  const text = atob(source ?? "");
  const bytes = new Uint8Array(text.length);
  for (let index = 0; index < text.length; index += 1) {
    bytes[index] = text.charCodeAt(index);
  }
  return bytes;
};
const __muonExecutorRpc = async (
  request,
  data = __muonExecutorEmptyBytes,
  onStdout = null,
  onStderr = null,
) =>
  JSON.parse(
    await __muonCall(${JSON.stringify(capabilityId)}, ${JSON.stringify(functionPath)}, [
      JSON.stringify(request),
      data,
      0,
      __muonExecutorOwnerCallback,
      onStdout,
      onStderr,
    ]),
  );
const __muonExecutorDecodeWaitResult = (raw) => {
  const result = {
    processId: raw.processId,
    exitCode: raw.exitCode,
  };
  if (Object.prototype.hasOwnProperty.call(raw, "stdoutBase64")) {
    result.stdout = __muonExecutorFromBase64(raw.stdoutBase64);
  }
  if (Object.prototype.hasOwnProperty.call(raw, "stderrBase64")) {
    result.stderr = __muonExecutorFromBase64(raw.stderrBase64);
  }
  return result;
};
const __muonExecutorReleaseActiveProcesses = async () => {
  if (__muonExecutorActiveProcesses.size === 0) {
    return;
  }
  for (const handle of Array.from(__muonExecutorActiveProcesses)) {
    try {
      await handle.release();
    } catch {}
  }
};
if (typeof globalThis.addEventListener === "function") {
  for (const eventName of ["beforeunload", "pagehide", "unload"]) {
    globalThis.addEventListener(eventName, __muonExecutorReleaseActiveProcesses);
  }
}
export const spawn = async (options = {}) => {
  const stdoutCallback =
    typeof options.onStdout === "function"
      ? (chunk) => options.onStdout(new Uint8Array(chunk))
      : null;
  const stderrCallback =
    typeof options.onStderr === "function"
      ? (chunk) => options.onStderr(new Uint8Array(chunk))
      : null;
  const start = await __muonExecutorRpc(
    {
      op: "start",
      options: {
        command: options.command,
        args: options.args,
        cwd: options.cwd,
        env: options.env,
      },
      captureStdout: stdoutCallback === null,
      captureStderr: stderrCallback === null,
    },
    __muonExecutorEmptyBytes,
    stdoutCallback,
    stderrCallback,
  );
  const handleId = start.handleId;
  let released = false;
  let stdinClosing = false;
  let waitPromise = null;
  const release = async () => {
    if (released) {
      return;
    }
    released = true;
    __muonExecutorActiveProcesses.delete(handle);
    await __muonExecutorRpc({ op: "dispose", handleId });
  };
  const handle = {
    processId: start.processId,
    writeStdin: async (data) => {
      if (released) {
        throw new Error("executor process is released");
      }
      if (stdinClosing) {
        throw new Error("stdin is closed");
      }
      await __muonExecutorRpc(
        { op: "writeStdin", handleId },
        __muonExecutorToBytes(data),
      );
    },
    closeStdin: async () => {
      if (released) {
        throw new Error("executor process is released");
      }
      stdinClosing = true;
      await __muonExecutorRpc({ op: "closeStdin", handleId });
    },
    wait: () => {
      if (waitPromise !== null) {
        return waitPromise;
      }
      waitPromise = (async () => {
        const result = __muonExecutorDecodeWaitResult(
          await __muonExecutorRpc({ op: "wait", handleId }),
        );
        if (!released) {
          released = true;
          __muonExecutorActiveProcesses.delete(handle);
          try {
            await __muonExecutorRpc({ op: "dispose", handleId });
          } catch {}
        }
        return result;
      })();
      return waitPromise;
    },
    kill: async () => {
      if (released) {
        throw new Error("executor process is released");
      }
      await __muonExecutorRpc({ op: "kill", handleId });
    },
    release,
  };
  if (__muonExecutorAsyncDispose !== null) {
    Object.defineProperty(handle, __muonExecutorAsyncDispose, {
      configurable: false,
      enumerable: false,
      value: release,
      writable: false,
    });
  }
  Object.freeze(handle);
  __muonExecutorActiveProcesses.add(handle);
  return handle;
};`;

const createExecutorLoadLibraryExport = (
  capabilityId: string,
  functionPath: string,
): string => `const __muonAdhocActiveLibraries = new Set();
const __muonAdhocEmptyBytes = new Uint8Array(0);
const __muonAdhocAsyncDispose =
  typeof Symbol === "function" && typeof Symbol.asyncDispose === "symbol"
    ? Symbol.asyncDispose
    : null;
const __muonAdhocPointerBrand =
  typeof Symbol === "function" ? Symbol.for("muon.nativePointer") : "__muonNativePointer";
const __muonAdhocType = (name) => Object.freeze({ name });
const __muonAdhocTypes = Object.freeze({
  voidType: __muonAdhocType("void"),
  boolType: __muonAdhocType("bool"),
  int8Type: __muonAdhocType("int8"),
  uint8Type: __muonAdhocType("uint8"),
  int16Type: __muonAdhocType("int16"),
  uint16Type: __muonAdhocType("uint16"),
  int32Type: __muonAdhocType("int32"),
  uint32Type: __muonAdhocType("uint32"),
  int64Type: __muonAdhocType("int64"),
  uint64Type: __muonAdhocType("uint64"),
  float32Type: __muonAdhocType("float32"),
  float64Type: __muonAdhocType("float64"),
  stringType: __muonAdhocType("string"),
  pointerType: __muonAdhocType("pointer"),
  bufferViewType: __muonAdhocType("bufferView"),
  usizeType: __muonAdhocType("usize"),
});
const __muonAdhocToBytes = (data) => {
  if (typeof data === "string") {
    return new TextEncoder().encode(data);
  }
  if (data instanceof ArrayBuffer) {
    return new Uint8Array(data);
  }
  if (ArrayBuffer.isView(data)) {
    return new Uint8Array(data.buffer, data.byteOffset, data.byteLength);
  }
  throw new TypeError("bufferView argument must be a string or BufferSource");
};
const __muonAdhocFromBase64 = (source) => {
  const text = atob(source ?? "");
  const bytes = new Uint8Array(text.length);
  for (let index = 0; index < text.length; index += 1) {
    bytes[index] = text.charCodeAt(index);
  }
  return bytes;
};
const __muonAdhocCreatePointer = (value) => {
  const text = String(value ?? "0");
  const pointer = {
    [__muonAdhocPointerBrand]: true,
    value: text,
    toString: () => text,
    toJSON: () => text,
  };
  return Object.freeze(pointer);
};
const __muonAdhocNormalizeType = (type) => {
  if (typeof type === "string") {
    return { name: type };
  }
  if (type && typeof type.name === "string") {
    return { name: type.name };
  }
  throw new TypeError("adhoc type descriptor is invalid");
};
const __muonAdhocNormalizeSignature = (signature) => {
  if (!signature || !Array.isArray(signature.argTypes)) {
    throw new TypeError("adhoc signature is invalid");
  }
  return {
    argTypes: signature.argTypes.map(__muonAdhocNormalizeType),
    returnType: __muonAdhocNormalizeType(signature.returnType),
  };
};
const __muonAdhocEncodeInteger = (value) => {
  if (typeof value === "bigint") {
    return value.toString();
  }
  if (typeof value === "number") {
    if (!Number.isFinite(value) || Math.trunc(value) !== value) {
      throw new TypeError("integer argument must be finite");
    }
    return String(value);
  }
  if (typeof value === "string") {
    return value;
  }
  throw new TypeError("integer argument must be a number, bigint, or string");
};
const __muonAdhocEncodePointer = (value) => {
  if (value === null || value === undefined) {
    return "0";
  }
  if (typeof value === "object" && value[__muonAdhocPointerBrand]) {
    return value.value;
  }
  return __muonAdhocEncodeInteger(value);
};
const __muonAdhocEncodeCall = (signature, args) => {
  if (args.length !== signature.argTypes.length) {
    throw new TypeError("Invalid adhoc argument count");
  }
  const encoded = [];
  const chunks = [];
  const bufferViews = [];
  let offset = 0;
  for (let index = 0; index < args.length; index += 1) {
    const name = signature.argTypes[index].name;
    const value = args[index];
    if (name === "int64" || name === "uint64" || name === "usize") {
      encoded.push(__muonAdhocEncodeInteger(value));
    } else if (name === "pointer") {
      encoded.push(__muonAdhocEncodePointer(value));
    } else if (name === "bufferView") {
      const bytes = __muonAdhocToBytes(value);
      chunks.push(bytes);
      bufferViews.push({ argIndex: index, offset, size: bytes.byteLength });
      offset += bytes.byteLength;
      encoded.push(null);
    } else {
      encoded.push(value);
    }
  }
  const data = new Uint8Array(offset);
  let writeOffset = 0;
  for (const chunk of chunks) {
    data.set(chunk, writeOffset);
    writeOffset += chunk.byteLength;
  }
  return { args: encoded, bufferViews, data };
};
const __muonAdhocDecodeResult = (signature, raw) => {
  const name = signature.returnType.name;
  if (name === "void") {
    return undefined;
  }
  if (name === "pointer") {
    return __muonAdhocCreatePointer(raw.pointer);
  }
  if (name === "int64" || name === "uint64" || name === "usize") {
    return BigInt(raw.value);
  }
  if (name === "bufferView") {
    return __muonAdhocFromBase64(raw.base64);
  }
  return raw.value;
};
const __muonAdhocRpc = async (request, data = __muonAdhocEmptyBytes) =>
  JSON.parse(
    await __muonCall(${JSON.stringify(capabilityId)}, ${JSON.stringify(functionPath)}, [
      JSON.stringify(request),
      data,
      0,
    ]),
  );
const __muonAdhocReleaseActiveLibraries = async () => {
  if (__muonAdhocActiveLibraries.size === 0) {
    return;
  }
  for (const handle of Array.from(__muonAdhocActiveLibraries)) {
    try {
      await handle.release();
    } catch {}
  }
};
if (typeof globalThis.addEventListener === "function") {
  for (const eventName of ["beforeunload", "pagehide", "unload"]) {
    globalThis.addEventListener(eventName, __muonAdhocReleaseActiveLibraries);
  }
}
export const voidType = __muonAdhocTypes.voidType;
export const boolType = __muonAdhocTypes.boolType;
export const int8Type = __muonAdhocTypes.int8Type;
export const uint8Type = __muonAdhocTypes.uint8Type;
export const int16Type = __muonAdhocTypes.int16Type;
export const uint16Type = __muonAdhocTypes.uint16Type;
export const int32Type = __muonAdhocTypes.int32Type;
export const uint32Type = __muonAdhocTypes.uint32Type;
export const int64Type = __muonAdhocTypes.int64Type;
export const uint64Type = __muonAdhocTypes.uint64Type;
export const float32Type = __muonAdhocTypes.float32Type;
export const float64Type = __muonAdhocTypes.float64Type;
export const stringType = __muonAdhocTypes.stringType;
export const pointerType = __muonAdhocTypes.pointerType;
export const bufferViewType = __muonAdhocTypes.bufferViewType;
export const usizeType = __muonAdhocTypes.usizeType;
export const loadLibrary = async (path) => {
  const start = await __muonAdhocRpc({ op: "load", path });
  const libraryId = start.libraryId;
  let released = false;
  const release = async () => {
    if (released) {
      return;
    }
    released = true;
    __muonAdhocActiveLibraries.delete(handle);
    await __muonAdhocRpc({ op: "release", libraryId });
  };
  const handle = {
    getFunction: async (name, signature) => {
      if (released) {
        throw new Error("adhoc library is released");
      }
      const normalizedSignature = __muonAdhocNormalizeSignature(signature);
      const loaded = await __muonAdhocRpc({
        op: "getFunction",
        libraryId,
        name,
        signature: normalizedSignature,
      });
      const functionId = loaded.functionId;
      return async (...args) => {
        if (released) {
          throw new Error("adhoc library is released");
        }
        const encoded = __muonAdhocEncodeCall(normalizedSignature, args);
        const raw = await __muonAdhocRpc(
          {
            op: "call",
            libraryId,
            functionId,
            args: encoded.args,
            bufferViews: encoded.bufferViews,
          },
          encoded.data,
        );
        return __muonAdhocDecodeResult(normalizedSignature, raw);
      };
    },
    release,
  };
  if (__muonAdhocAsyncDispose !== null) {
    Object.defineProperty(handle, __muonAdhocAsyncDispose, {
      configurable: false,
      enumerable: false,
      value: release,
      writable: false,
    });
  }
  Object.freeze(handle);
  __muonAdhocActiveLibraries.add(handle);
  return handle;
};`;

const createBrowserContextMenuHelpers =
  (): string => `const __muonBrowserContextMenuEventName = "muon-browser-context-menu-command";
const __muonBrowserContextMenuWhenKeys = [
  "editable",
  "selection",
  "link",
  "image",
  "canCopy",
  "canPaste",
];
let __muonBrowserContextMenuToken = "";
let __muonBrowserContextMenuHandler = undefined;
let __muonBrowserContextMenuListening = false;
const __muonCreateBrowserContextMenuToken = () => {
  const crypto = globalThis.crypto;
  if (
    crypto &&
    typeof crypto.getRandomValues === "function" &&
    typeof globalThis.Uint32Array === "function"
  ) {
    const values = new globalThis.Uint32Array(4);
    crypto.getRandomValues(values);
    return Array.from(values, (value) => value.toString(16).padStart(8, "0")).join("");
  }
  return \`\${Date.now().toString(36)}-\${Math.random().toString(36).slice(2)}\`;
};
const __muonEnsureBrowserContextMenuListener = () => {
  if (
    __muonBrowserContextMenuListening ||
    typeof globalThis.addEventListener !== "function"
  ) {
    return;
  }
  globalThis.addEventListener(__muonBrowserContextMenuEventName, (event) => {
    const detail = event && event.detail;
    if (
      typeof detail !== "object" ||
      detail === null ||
      detail.token !== __muonBrowserContextMenuToken ||
      typeof __muonBrowserContextMenuHandler !== "function"
    ) {
      return;
    }
    __muonBrowserContextMenuHandler(detail);
  });
  __muonBrowserContextMenuListening = true;
};
const __muonNormalizeBrowserContextMenuPlacement = (placement) => {
  if (placement === undefined) {
    return undefined;
  }
  if (placement === "start" || placement === "afterEdit" || placement === "end") {
    return placement;
  }
  throw new TypeError("Invalid context menu placement");
};
const __muonNormalizeBrowserContextMenuWhen = (when) => {
  if (when === undefined) {
    return undefined;
  }
  if (typeof when !== "object" || when === null || Array.isArray(when)) {
    throw new TypeError("Invalid context menu condition");
  }
  const normalized = {};
  for (const key of __muonBrowserContextMenuWhenKeys) {
    const value = when[key];
    if (value === undefined) {
      continue;
    }
    if (typeof value !== "boolean") {
      throw new TypeError("Invalid context menu condition");
    }
    normalized[key] = value;
  }
  return normalized;
};
const __muonNormalizeBrowserContextMenuCommandId = (id) => {
  if (
    typeof id !== "string" ||
    id === "" ||
    /[\\u0000-\\u001f]/u.test(id) ||
    id.startsWith("muon.") ||
    id.startsWith("standard.")
  ) {
    throw new TypeError("Invalid context menu item id");
  }
  return id;
};
const __muonNormalizeBrowserContextMenuItem = (item) => {
  if (typeof item !== "object" || item === null || Array.isArray(item)) {
    throw new TypeError("Invalid context menu item");
  }
  const placement = __muonNormalizeBrowserContextMenuPlacement(item.placement);
  const when = __muonNormalizeBrowserContextMenuWhen(item.when);
  if (item.type === "separator") {
    return {
      type: "separator",
      ...(placement === undefined ? {} : { placement }),
      ...(when === undefined ? {} : { when }),
    };
  }
  if (item.type !== undefined && item.type !== "item") {
    throw new TypeError("Invalid context menu item type");
  }
  if (typeof item.label !== "string" || item.label === "") {
    throw new TypeError("Invalid context menu item label");
  }
  if (item.enabled !== undefined && typeof item.enabled !== "boolean") {
    throw new TypeError("Invalid context menu item enabled state");
  }
  return {
    id: __muonNormalizeBrowserContextMenuCommandId(item.id),
    label: item.label,
    enabled: item.enabled === undefined ? true : item.enabled,
    ...(placement === undefined ? {} : { placement }),
    ...(when === undefined ? {} : { when }),
  };
};
const __muonNormalizeBrowserContextMenuItems = (items) => {
  if (!Array.isArray(items)) {
    throw new TypeError("Invalid context menu items");
  }
  return items.map(__muonNormalizeBrowserContextMenuItem);
};`;

const createBrowserSetContextMenuItemsExport = (
  capabilityId: string,
  functionPath: string,
): string => `export const setContextMenuItems = async (items, handler = undefined) => {
  if (handler !== undefined && typeof handler !== "function") {
    throw new TypeError("Invalid context menu handler");
  }
  const normalized = __muonNormalizeBrowserContextMenuItems(items);
  const token = __muonCreateBrowserContextMenuToken();
  await __muonCall(${JSON.stringify(capabilityId)}, ${JSON.stringify(functionPath)}, [JSON.stringify(normalized), token]);
  __muonBrowserContextMenuToken = token;
  __muonBrowserContextMenuHandler = handler;
  __muonEnsureBrowserContextMenuListener();
};`;

const createBrowserClearContextMenuItemsExport = (
  capabilityId: string,
  functionPath: string,
): string => `export const clearContextMenuItems = async () => {
  __muonBrowserContextMenuToken = "";
  __muonBrowserContextMenuHandler = undefined;
  await __muonCall(${JSON.stringify(capabilityId)}, ${JSON.stringify(functionPath)}, []);
};`;

const createBrowserTrayHelpers =
  (): string => `const __muonBrowserTrayEventName = "muon-browser-tray-event";
const __muonBrowserTrayHandlers = new Map();
let __muonBrowserTrayListening = false;
const __muonCreateBrowserTrayToken = () => {
  const crypto = globalThis.crypto;
  if (
    crypto &&
    typeof crypto.getRandomValues === "function" &&
    typeof globalThis.Uint32Array === "function"
  ) {
    const values = new globalThis.Uint32Array(4);
    crypto.getRandomValues(values);
    return Array.from(values, (value) => value.toString(16).padStart(8, "0")).join("");
  }
  return \`\${Date.now().toString(36)}-\${Math.random().toString(36).slice(2)}\`;
};
const __muonEnsureBrowserTrayListener = () => {
  if (
    __muonBrowserTrayListening ||
    typeof globalThis.addEventListener !== "function"
  ) {
    return;
  }
  globalThis.addEventListener(__muonBrowserTrayEventName, (event) => {
    const detail = event && event.detail;
    if (
      typeof detail !== "object" ||
      detail === null ||
      typeof detail.trayId !== "string"
    ) {
      return;
    }
    const entry = __muonBrowserTrayHandlers.get(detail.trayId);
    if (
      entry === undefined ||
      detail.token !== entry.token ||
      typeof entry.handler !== "function"
    ) {
      return;
    }
    entry.handler(detail);
  });
  __muonBrowserTrayListening = true;
};
const __muonNormalizeBrowserTrayId = (id) => {
  if (
    typeof id !== "string" ||
    id === "" ||
    /[\\u0000-\\u001f]/u.test(id) ||
    id.startsWith("muon.") ||
    id.startsWith("standard.")
  ) {
    throw new TypeError("Invalid tray id");
  }
  return id;
};
const __muonNormalizeBrowserTrayMenuItem = (item) => {
  if (typeof item !== "object" || item === null || Array.isArray(item)) {
    throw new TypeError("Invalid tray menu item");
  }
  if (item.type === "separator") {
    return { type: "separator" };
  }
  const type = item.type === undefined ? "item" : item.type;
  if (type !== "item" && type !== "checkbox" && type !== "radio") {
    throw new TypeError("Invalid tray menu item type");
  }
  if (typeof item.label !== "string" || item.label === "") {
    throw new TypeError("Invalid tray menu item label");
  }
  if (item.enabled !== undefined && typeof item.enabled !== "boolean") {
    throw new TypeError("Invalid tray menu item enabled state");
  }
  if (item.checked !== undefined && typeof item.checked !== "boolean") {
    throw new TypeError("Invalid tray menu item checked state");
  }
  if (type === "item" && item.checked !== undefined) {
    throw new TypeError("Invalid tray menu item checked state");
  }
  return {
    ...(type === "item" ? {} : { type }),
    id: __muonNormalizeBrowserTrayId(item.id),
    label: item.label,
    enabled: item.enabled === undefined ? true : item.enabled,
    ...(item.checked === undefined ? {} : { checked: item.checked }),
  };
};
const __muonNormalizeBrowserTrayMenuItems = (items) => {
  if (!Array.isArray(items)) {
    throw new TypeError("Invalid tray menu items");
  }
  return items.map(__muonNormalizeBrowserTrayMenuItem);
};
const __muonNormalizeBrowserTrayOptions = (options) => {
  if (typeof options !== "object" || options === null || Array.isArray(options)) {
    throw new TypeError("Invalid tray options");
  }
  const hasIcon = options.icon !== undefined;
  if (hasIcon && (typeof options.icon !== "string" || options.icon === "")) {
    throw new TypeError("Invalid tray icon");
  }
  if (options.tooltip !== undefined && options.tooltip !== null && typeof options.tooltip !== "string") {
    throw new TypeError("Invalid tray tooltip");
  }
  return {
    ...(options.id === undefined ? {} : { id: __muonNormalizeBrowserTrayId(options.id) }),
    ...(hasIcon ? { icon: options.icon } : {}),
    ...(options.tooltip === undefined || options.tooltip === null ? {} : { tooltip: options.tooltip }),
    ...(options.menu === undefined ? {} : { menu: __muonNormalizeBrowserTrayMenuItems(options.menu) }),
  };
};`;

const createBrowserCreateTrayExport = (
  capabilityId: string,
  functionPath: string,
): string => `export const createTray = async (options, handler = undefined) => {
  if (handler !== undefined && typeof handler !== "function") {
    throw new TypeError("Invalid tray handler");
  }
  const normalized = __muonNormalizeBrowserTrayOptions(options);
  const token = __muonCreateBrowserTrayToken();
  const trayId = await __muonCall(${JSON.stringify(capabilityId)}, ${JSON.stringify(functionPath)}, [JSON.stringify(normalized), token]);
  __muonBrowserTrayHandlers.set(trayId, { token, handler });
  __muonEnsureBrowserTrayListener();
  return trayId;
};`;

const createBrowserSetTrayMenuExport = (
  capabilityId: string,
  functionPath: string,
): string => `export const setTrayMenu = async (id, items, handler = undefined) => {
  if (handler !== undefined && typeof handler !== "function") {
    throw new TypeError("Invalid tray handler");
  }
  const trayId = __muonNormalizeBrowserTrayId(id);
  const normalized = __muonNormalizeBrowserTrayMenuItems(items);
  const token = __muonCreateBrowserTrayToken();
  await __muonCall(${JSON.stringify(capabilityId)}, ${JSON.stringify(functionPath)}, [trayId, JSON.stringify(normalized), token]);
  __muonBrowserTrayHandlers.set(trayId, { token, handler });
  __muonEnsureBrowserTrayListener();
};`;

const createBrowserSetTrayIconExport = (
  capabilityId: string,
  functionPath: string,
): string => `export const setTrayIcon = async (id, iconPath) => {
  const trayId = __muonNormalizeBrowserTrayId(id);
  if (typeof iconPath !== "string" || iconPath === "") {
    throw new TypeError("Invalid tray icon");
  }
  await __muonCall(${JSON.stringify(capabilityId)}, ${JSON.stringify(functionPath)}, [trayId, iconPath]);
};`;

const createBrowserSetTrayTooltipExport = (
  capabilityId: string,
  functionPath: string,
): string => `export const setTrayTooltip = async (id, tooltip) => {
  const trayId = __muonNormalizeBrowserTrayId(id);
  if (tooltip !== null && typeof tooltip !== "string") {
    throw new TypeError("Invalid tray tooltip");
  }
  await __muonCall(${JSON.stringify(capabilityId)}, ${JSON.stringify(functionPath)}, [trayId, tooltip === null ? "" : tooltip]);
};`;

const createBrowserRemoveTrayExport = (
  capabilityId: string,
  functionPath: string,
): string => `export const removeTray = async (id) => {
  const trayId = __muonNormalizeBrowserTrayId(id);
  await __muonCall(${JSON.stringify(capabilityId)}, ${JSON.stringify(functionPath)}, [trayId]);
  __muonBrowserTrayHandlers.delete(trayId);
};`;

const createGenericFunctionExport = (
  exportName: string,
  capabilityId: string,
  functionPath: string,
): string => `export const ${exportName} = async (...args) =>
  await __muonCall(${JSON.stringify(capabilityId)}, ${JSON.stringify(functionPath)}, args);`;

const createEnvironmentsGetConfigValuesExport = (
  capabilityId: string,
  functionPath: string,
): string =>
  `export const getConfigValues = async () => JSON.parse(await __muonCall(${JSON.stringify(capabilityId)}, ${JSON.stringify(functionPath)}, []));`;

const createModuleSource = (rule: ResolvedRule): string => {
  const exportedFunctions = getExportedFunctions(
    rule.namespace,
    rule.rule.allow,
    rule.functionPaths,
  );
  if (exportedFunctions.length === 0) {
    const hasWildcardAllow = rule.rule.allow.some(containsGlob);
    throw new Error(
      hasWildcardAllow
        ? `muon capability import has no matching function exports: ${rule.moduleName}`
        : `muon capability import has no exact function exports: ${rule.moduleName}`,
    );
  }

  const usesBrowserContextMenuHelpers = exportedFunctions.some(
    ([exportName]) =>
      rule.namespace === "muon.browser" &&
      (exportName === "setContextMenuItems" ||
        exportName === "clearContextMenuItems"),
  );
  const usesBrowserTrayHelpers = exportedFunctions.some(
    ([exportName]) =>
      rule.namespace === "muon.browser" &&
      (exportName === "createTray" ||
        exportName === "setTrayMenu" ||
        exportName === "setTrayIcon" ||
        exportName === "setTrayTooltip" ||
        exportName === "removeTray"),
  );
  const exports = exportedFunctions.map(([exportName, functionPath]) => {
    if (
      rule.namespace === "muon.environments" &&
      exportName === "getConfigValues"
    ) {
      return createEnvironmentsGetConfigValuesExport(rule.id, functionPath);
    }
    if (rule.namespace === "muon.executor" && exportName === "spawn") {
      return createExecutorSpawnExport(rule.id, functionPath);
    }
    if (rule.namespace === "muon.executor" && exportName === "loadLibrary") {
      return createExecutorLoadLibraryExport(rule.id, functionPath);
    }
    if (
      rule.namespace === "muon.browser" &&
      exportName === "setContextMenuItems"
    ) {
      return createBrowserSetContextMenuItemsExport(rule.id, functionPath);
    }
    if (
      rule.namespace === "muon.browser" &&
      exportName === "clearContextMenuItems"
    ) {
      return createBrowserClearContextMenuItemsExport(rule.id, functionPath);
    }
    if (rule.namespace === "muon.browser" && exportName === "createTray") {
      return createBrowserCreateTrayExport(rule.id, functionPath);
    }
    if (rule.namespace === "muon.browser" && exportName === "setTrayMenu") {
      return createBrowserSetTrayMenuExport(rule.id, functionPath);
    }
    if (rule.namespace === "muon.browser" && exportName === "setTrayIcon") {
      return createBrowserSetTrayIconExport(rule.id, functionPath);
    }
    if (rule.namespace === "muon.browser" && exportName === "setTrayTooltip") {
      return createBrowserSetTrayTooltipExport(rule.id, functionPath);
    }
    if (rule.namespace === "muon.browser" && exportName === "removeTray") {
      return createBrowserRemoveTrayExport(rule.id, functionPath);
    }
    return createGenericFunctionExport(exportName, rule.id, functionPath);
  });
  return `const __muonCall = globalThis.__muon_plugin_call;
if (typeof __muonCall !== "function") {
  throw new Error("muon plugin capability bridge is not available.");
}

${usesBrowserContextMenuHelpers ? `${createBrowserContextMenuHelpers()}\n\n` : ""}
${usesBrowserTrayHelpers ? `${createBrowserTrayHelpers()}\n\n` : ""}
${exports.join("\n\n")}
`;
};

/**
 * Creates a capability virtual module resolver for a bundler adapter.
 *
 * @param root Bundler project root.
 * @param options Capability import options.
 */
export const createMuonCapabilityModuleResolver = (
  root: string,
  options: MuonCapabilityOptions | undefined,
): MuonCapabilityModuleResolver => {
  const rules = [...(options?.imports ?? [])];
  const functionPaths = createFunctionPathCatalog(options?.functionPaths);
  for (const rule of rules) {
    validateCapabilityRule(rule);
  }
  const usedCapabilityIds = new Set<string>();
  const runtimeEntries = rules.map((rule) =>
    createRuleRuntimeEntry(rule, createCapabilityId(usedCapabilityIds)),
  );

  const resolveRule = (
    source: string,
    importer: string | undefined,
  ): ResolvedRule | undefined => {
    const parsed = parseCapabilitySpecifier(source);
    if (parsed === undefined) {
      return undefined;
    }
    const namespaceConfigured = rules.some((rule) =>
      hasNamespaceFunctionAllow(parsed.namespace, rule.allow),
    );
    if (!namespaceConfigured) {
      return undefined;
    }
    if (importer === undefined) {
      throw new Error(
        `muon capability import is not allowed without an importer: ${source}`,
      );
    }

    const relativeImporter = toRootRelativeImporter(root, importer);
    for (let index = 0; index < rules.length; index += 1) {
      const rule = rules[index];
      const runtimeEntry = runtimeEntries[index];
      if (
        rule === undefined ||
        runtimeEntry === undefined ||
        !matchesCapabilityRuleImporter(rule, root, importer) ||
        !hasNamespaceFunctionAllow(parsed.namespace, rule.allow)
      ) {
        continue;
      }
      return {
        index,
        id: runtimeEntry.id,
        rule,
        namespace: parsed.namespace,
        moduleName: parsed.moduleName,
        functionPaths,
      };
    }

    throw new Error(
      `muon capability import is not allowed: ${source} from ${relativeImporter}`,
    );
  };

  return {
    resolveId: (source, importer) => {
      const rule = resolveRule(source, importer);
      return rule === undefined
        ? undefined
        : {
            id: createModuleVirtualId(rule),
          };
    },
    load: (id) => {
      const parsed = parseModuleVirtualId(id);
      if (parsed === undefined) {
        return undefined;
      }
      const source = parseCapabilitySpecifier(parsed.moduleName);
      const rule = rules[parsed.index];
      const runtimeEntry = runtimeEntries[parsed.index];
      if (
        source === undefined ||
        rule === undefined ||
        runtimeEntry === undefined
      ) {
        return undefined;
      }
      return createModuleSource({
        index: parsed.index,
        id: runtimeEntry.id,
        rule,
        namespace: source.namespace,
        moduleName: source.moduleName,
        functionPaths,
      });
    },
    getRuntimePluginConfig: () => ({
      mode: "validate",
      capabilities: runtimeEntries,
    }),
  };
};
