if(NOT DEFINED INPUT OR INPUT STREQUAL "")
  message(FATAL_ERROR "INPUT is required.")
endif()
if(NOT DEFINED OUTPUT OR OUTPUT STREQUAL "")
  message(FATAL_ERROR "OUTPUT is required.")
endif()
if(NOT EXISTS "${OUTPUT}")
  get_filename_component(OUTPUT_DIR "${OUTPUT}" DIRECTORY)
  file(MAKE_DIRECTORY "${OUTPUT_DIR}")
  file(COPY_FILE "${INPUT}" "${OUTPUT}")
endif()
