if(NOT DEFINED OUTPUT OR OUTPUT STREQUAL "")
  message(FATAL_ERROR "OUTPUT is required.")
endif()
if(NOT DEFINED KEYBIND_NAME OR KEYBIND_NAME STREQUAL "")
  message(FATAL_ERROR "KEYBIND_NAME is required.")
endif()
if(NOT DEFINED KEYBIND_VALUE OR KEYBIND_VALUE STREQUAL "")
  message(FATAL_ERROR "KEYBIND_VALUE is required.")
endif()
if(NOT EXISTS "${OUTPUT}")
  message(FATAL_ERROR "OUTPUT does not exist: ${OUTPUT}")
endif()

file(READ "${OUTPUT}" MUON_CONFIG_JSON)

string(JSON MUON_BROWSER_TYPE ERROR_VARIABLE MUON_BROWSER_TYPE_ERROR
  TYPE "${MUON_CONFIG_JSON}" browser)
if(MUON_BROWSER_TYPE_ERROR OR MUON_BROWSER_TYPE STREQUAL "NOTFOUND")
  string(JSON MUON_CONFIG_JSON SET "${MUON_CONFIG_JSON}" browser "{}")
elseif(NOT MUON_BROWSER_TYPE STREQUAL "OBJECT")
  message(FATAL_ERROR "muon.json browser must be an object: ${OUTPUT}")
endif()

string(JSON MUON_KEYBINDS_TYPE ERROR_VARIABLE MUON_KEYBINDS_TYPE_ERROR
  TYPE "${MUON_CONFIG_JSON}" browser keybind)
if(MUON_KEYBINDS_TYPE_ERROR OR MUON_KEYBINDS_TYPE STREQUAL "NOTFOUND")
  string(JSON MUON_CONFIG_JSON SET "${MUON_CONFIG_JSON}" browser keybind "{}")
elseif(NOT MUON_KEYBINDS_TYPE STREQUAL "OBJECT")
  message(FATAL_ERROR "muon.json browser.keybind must be an object: ${OUTPUT}")
endif()

string(JSON MUON_KEYBIND_TYPE ERROR_VARIABLE MUON_KEYBIND_TYPE_ERROR
  TYPE "${MUON_CONFIG_JSON}" browser keybind "${KEYBIND_NAME}")
if(NOT MUON_KEYBIND_TYPE_ERROR AND NOT MUON_KEYBIND_TYPE STREQUAL "NOTFOUND")
  return()
endif()

string(JSON MUON_CONFIG_JSON SET "${MUON_CONFIG_JSON}"
  browser keybind "${KEYBIND_NAME}" "\"${KEYBIND_VALUE}\"")
file(WRITE "${OUTPUT}" "${MUON_CONFIG_JSON}\n")
