if(NOT DEFINED OUTPUT OR OUTPUT STREQUAL "")
  message(FATAL_ERROR "OUTPUT is required.")
endif()
if(NOT DEFINED PLUGIN_NAME OR PLUGIN_NAME STREQUAL "")
  message(FATAL_ERROR "PLUGIN_NAME is required.")
endif()
if(NOT DEFINED PLUGIN_ALLOW OR PLUGIN_ALLOW STREQUAL "")
  message(FATAL_ERROR "PLUGIN_ALLOW is required.")
endif()
if(NOT EXISTS "${OUTPUT}")
  message(FATAL_ERROR "OUTPUT does not exist: ${OUTPUT}")
endif()

file(READ "${OUTPUT}" MUON_CONFIG_JSON)

string(JSON MUON_PLUGIN_TYPE ERROR_VARIABLE MUON_PLUGIN_TYPE_ERROR
  TYPE "${MUON_CONFIG_JSON}" plugin)
if(MUON_PLUGIN_TYPE_ERROR OR MUON_PLUGIN_TYPE STREQUAL "NOTFOUND")
  string(JSON MUON_CONFIG_JSON SET "${MUON_CONFIG_JSON}" plugin "{}")
elseif(NOT MUON_PLUGIN_TYPE STREQUAL "OBJECT")
  message(FATAL_ERROR "muon.json plugin must be an object: ${OUTPUT}")
endif()

string(JSON MUON_PLUGIN_PATH_TYPE ERROR_VARIABLE MUON_PLUGIN_PATH_TYPE_ERROR
  TYPE "${MUON_CONFIG_JSON}" plugin path)
if(MUON_PLUGIN_PATH_TYPE_ERROR OR MUON_PLUGIN_PATH_TYPE STREQUAL "NOTFOUND")
  string(JSON MUON_CONFIG_JSON SET "${MUON_CONFIG_JSON}" plugin path "\"./plugins\"")
endif()

string(JSON MUON_PLUGINS_TYPE ERROR_VARIABLE MUON_PLUGINS_TYPE_ERROR
  TYPE "${MUON_CONFIG_JSON}" plugin plugins)
if(MUON_PLUGINS_TYPE_ERROR OR MUON_PLUGINS_TYPE STREQUAL "NOTFOUND")
  string(JSON MUON_CONFIG_JSON SET "${MUON_CONFIG_JSON}" plugin plugins "[]")
elseif(NOT MUON_PLUGINS_TYPE STREQUAL "ARRAY")
  message(FATAL_ERROR "muon.json plugin.plugins must be an array: ${OUTPUT}")
endif()

string(JSON MUON_PLUGIN_COUNT LENGTH "${MUON_CONFIG_JSON}" plugin plugins)
math(EXPR MUON_PLUGIN_LAST_INDEX "${MUON_PLUGIN_COUNT} - 1")
if(MUON_PLUGIN_LAST_INDEX GREATER_EQUAL 0)
  foreach(MUON_PLUGIN_INDEX RANGE 0 ${MUON_PLUGIN_LAST_INDEX})
    string(JSON MUON_ENTRY_NAME ERROR_VARIABLE MUON_ENTRY_NAME_ERROR
      GET "${MUON_CONFIG_JSON}" plugin plugins ${MUON_PLUGIN_INDEX} name)
    if(NOT MUON_ENTRY_NAME_ERROR AND MUON_ENTRY_NAME STREQUAL PLUGIN_NAME)
      return()
    endif()
  endforeach()
endif()

set(MUON_STANDARD_PLUGIN_ENTRY
  "{\"name\":\"${PLUGIN_NAME}\",\"allow\":[\"${PLUGIN_ALLOW}\"]}")
string(JSON MUON_CONFIG_JSON SET "${MUON_CONFIG_JSON}"
  plugin plugins ${MUON_PLUGIN_COUNT} "${MUON_STANDARD_PLUGIN_ENTRY}")
file(WRITE "${OUTPUT}" "${MUON_CONFIG_JSON}\n")
