if(NOT DEFINED INPUT OR INPUT STREQUAL "")
  message(FATAL_ERROR "INPUT is required.")
endif()
if(NOT DEFINED OUTPUT OR OUTPUT STREQUAL "")
  message(FATAL_ERROR "OUTPUT is required.")
endif()

file(READ "${INPUT}" MUON_CEF_PREPARE_JSON)
string(JSON MUON_CEF_ARTIFACT_FILE_NAME GET
  "${MUON_CEF_PREPARE_JSON}" artifact fileName)
string(JSON MUON_CEF_ARTIFACT_URL GET
  "${MUON_CEF_PREPARE_JSON}" artifact url)
string(JSON MUON_CEF_ARTIFACT_SHA1 GET
  "${MUON_CEF_PREPARE_JSON}" artifact sha1)
string(JSON MUON_CEF_ARTIFACT_SIZE GET
  "${MUON_CEF_PREPARE_JSON}" artifact size)

file(WRITE "${OUTPUT}"
  "${MUON_CEF_ARTIFACT_FILE_NAME}\n"
  "${MUON_CEF_ARTIFACT_URL}\n"
  "${MUON_CEF_ARTIFACT_SHA1}\n"
  "${MUON_CEF_ARTIFACT_SIZE}\n")
