if(NOT DEFINED MUON_ARTIFACT OR MUON_ARTIFACT STREQUAL "")
  message(FATAL_ERROR "MUON_ARTIFACT is required.")
endif()
if(NOT DEFINED MUON_BUILD_DIRECTORY OR MUON_BUILD_DIRECTORY STREQUAL "")
  message(FATAL_ERROR "MUON_BUILD_DIRECTORY is required.")
endif()

file(REAL_PATH "${MUON_ARTIFACT}" MUON_ARTIFACT_REAL)
file(REAL_PATH "${MUON_BUILD_DIRECTORY}" MUON_BUILD_DIRECTORY_REAL)
cmake_path(IS_PREFIX MUON_BUILD_DIRECTORY_REAL
  "${MUON_ARTIFACT_REAL}" NORMALIZE MUON_ARTIFACT_IS_BUILD_SCOPED)
if(NOT MUON_ARTIFACT_IS_BUILD_SCOPED)
  message(FATAL_ERROR
    "Build artifact is shared outside its build directory: ${MUON_ARTIFACT_REAL}")
endif()
